import { promises as fs } from "node:fs";
import path from "node:path";
import { z } from "zod";
import {
  aiCompactPathResponseSchema,
  aiExpansionResponseSchema,
  aiPathResponseSchema,
  type AiExpansionResponse,
  type AiPathResponse,
} from "./ai/schemas";
import type { GenerationProvider } from "./types";

/**
 * Reusable store of AI-generated content, keyed by subject.
 *
 * Caches the validated AI *response* rather than a built LearningPath so every
 * learner still gets freshly minted path/unit/lesson ids from the transform.
 *
 * Two layers, checked per entry: content generated by this process first, then
 * the committed content/library/*.json seeds from `npm run seed:content`.
 */

const LIBRARY_DIR = path.join(process.cwd(), "content", "library");
const ENTRY_VERSION = 1;

/** Max depth the expansion route can request; mirrors the cap in the expand route. */
const MAX_DEPTH = 4;

const providerSchema = z.enum(["groq", "gemini"]);

/**
 * Groq initial paths are validated against the compact schema (5-7 lessons,
 * shorter bodies), so a strict-only check here would silently drop every
 * Groq-seeded subject on read.
 */
const cachedPathResponseSchema = z.union([
  aiPathResponseSchema,
  aiCompactPathResponseSchema,
]);

const cachedPathEntrySchema = z.object({
  version: z.literal(ENTRY_VERSION),
  subject: z.string(),
  provider: providerSchema,
  generatedAt: z.string(),
  response: cachedPathResponseSchema,
});

const cachedExpansionEntrySchema = z.object({
  version: z.literal(ENTRY_VERSION),
  subject: z.string(),
  depth: z.number().int().min(1).max(MAX_DEPTH),
  provider: providerSchema,
  generatedAt: z.string(),
  /** Lesson titles that already existed when this unit was generated. */
  sourceTitles: z.array(z.string()),
  response: aiExpansionResponseSchema,
});

const libraryFileSchema = z.object({
  subject: z.string(),
  path: cachedPathEntrySchema.optional(),
  expansions: z.record(z.string(), cachedExpansionEntrySchema).default({}),
});

export type CachedPathEntry = z.infer<typeof cachedPathEntrySchema>;
export type CachedExpansionEntry = z.infer<typeof cachedExpansionEntrySchema>;
export type LibraryFile = z.infer<typeof libraryFileSchema>;

/**
 * Collapses surface differences so "Ancient Rome", "ancient rome" and
 * "  Ancient  Rome!  " share one library entry.
 */
export function subjectKey(subject: string): string {
  return subject
    .normalize("NFKD")
    .toLowerCase()
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80);
}

function normalizeTitle(title: string): string {
  return title.toLowerCase().replace(/\s+/g, " ").trim();
}

/** Content generated by this process, kept even when the disk layer has none. */
const runtime = new Map<string, LibraryFile>();

/** Parsed disk entries, revalidated by mtime so re-seeding takes effect live. */
const diskCache = new Map<string, { mtimeMs: number; file: LibraryFile }>();

export function libraryFilePath(key: string): string {
  return path.join(LIBRARY_DIR, `${key}.json`);
}

/** Reads and validates one library file. Malformed or missing files read as absent. */
async function readLibraryFile(key: string): Promise<LibraryFile | null> {
  const filePath = libraryFilePath(key);

  let mtimeMs: number;
  try {
    ({ mtimeMs } = await fs.stat(filePath));
  } catch {
    return null;
  }

  const cached = diskCache.get(key);
  if (cached && cached.mtimeMs === mtimeMs) return cached.file;

  try {
    const raw = await fs.readFile(filePath, "utf8");
    const file = libraryFileSchema.parse(JSON.parse(raw));
    diskCache.set(key, { mtimeMs, file });
    return file;
  } catch (error) {
    console.warn(`Curio: ignoring unreadable library entry "${key}"`, error);
    return null;
  }
}

/**
 * Looks up a single entry across both layers. Falling through per-entry (rather
 * than per-file) matters: a subject can have a runtime-generated path while its
 * deeper units come from the committed library, or vice versa.
 */
async function findEntry<T>(
  key: string,
  pick: (file: LibraryFile) => T | undefined,
): Promise<T | undefined> {
  const fromRuntime = runtime.get(key);
  if (fromRuntime) {
    const hit = pick(fromRuntime);
    if (hit) return hit;
  }

  const fromDisk = await readLibraryFile(key);
  return fromDisk ? pick(fromDisk) : undefined;
}

/** Merge base for writes, so persisting one entry never drops the others. */
async function baseFile(key: string, subject: string): Promise<LibraryFile> {
  const fromDisk = await readLibraryFile(key);
  const fromRuntime = runtime.get(key);
  return {
    subject,
    path: fromRuntime?.path ?? fromDisk?.path,
    expansions: { ...fromDisk?.expansions, ...fromRuntime?.expansions },
  };
}

export interface CacheHit<T> {
  data: T;
  provider: GenerationProvider;
  generatedAt: string;
}

export async function readCachedPath(
  subject: string,
): Promise<CacheHit<AiPathResponse> | null> {
  const entry = await findEntry(subjectKey(subject), (file) => file.path);
  if (!entry) return null;
  return {
    data: entry.response,
    provider: entry.provider,
    generatedAt: entry.generatedAt,
  };
}

/**
 * A cached unit is only safe to reuse when it teaches nothing the learner has
 * already seen — their earlier units may have come from a different provider
 * (or a compact Groq path) and covered different ground.
 */
function isReusable(entry: CachedExpansionEntry, existingTitles: string[]): boolean {
  const unit = entry.response.unit;

  // A cached "no material left" verdict only applies to a learner who has
  // covered at least as much as the path it was decided against, otherwise it
  // would cut a thinner path off early.
  if (!unit) return existingTitles.length >= entry.sourceTitles.length;

  const seen = new Set(existingTitles.map(normalizeTitle));
  return !unit.lessons.some((lesson) => seen.has(normalizeTitle(lesson.title)));
}

export async function readCachedExpansion(
  subject: string,
  depth: number,
  existingTitles: string[],
): Promise<CacheHit<AiExpansionResponse> | null> {
  const entry = await findEntry(
    subjectKey(subject),
    (file) => file.expansions[String(depth)],
  );
  if (!entry) return null;
  if (!isReusable(entry, existingTitles)) return null;

  return {
    data: entry.response,
    provider: entry.provider,
    generatedAt: entry.generatedAt,
  };
}

/**
 * Persisting to disk turns a dev session's generations into committable seeds.
 * Off by default, and never in production, where the filesystem is read-only.
 */
function shouldPersist(): boolean {
  return process.env.CURIO_CACHE_PERSIST === "1" && process.env.NODE_ENV !== "production";
}

async function persist(key: string, file: LibraryFile): Promise<void> {
  if (!shouldPersist()) return;
  try {
    await fs.mkdir(LIBRARY_DIR, { recursive: true });
    await fs.writeFile(libraryFilePath(key), `${JSON.stringify(file, null, 2)}\n`, "utf8");
  } catch (error) {
    console.warn(`Curio: could not persist library entry "${key}"`, error);
  }
}

export async function writeCachedPath(
  subject: string,
  response: AiPathResponse,
  provider: GenerationProvider,
): Promise<void> {
  const key = subjectKey(subject);
  if (!key) return;

  const updated: LibraryFile = {
    ...(await baseFile(key, subject)),
    path: buildPathEntry(subject, response, provider),
  };

  runtime.set(key, updated);
  await persist(key, updated);
}

export async function writeCachedExpansion(
  subject: string,
  depth: number,
  existingTitles: string[],
  response: AiExpansionResponse,
  provider: GenerationProvider,
): Promise<void> {
  const key = subjectKey(subject);
  if (!key || depth < 1 || depth > MAX_DEPTH) return;

  const file = await baseFile(key, subject);
  const updated: LibraryFile = {
    ...file,
    expansions: {
      ...file.expansions,
      [String(depth)]: buildExpansionEntry(
        subject,
        depth,
        existingTitles,
        response,
        provider,
      ),
    },
  };

  runtime.set(key, updated);
  await persist(key, updated);
}

/** Used by the seed script to write a whole subject in one pass. */
export async function writeLibraryFile(key: string, file: LibraryFile): Promise<void> {
  await fs.mkdir(LIBRARY_DIR, { recursive: true });
  await fs.writeFile(libraryFilePath(key), `${JSON.stringify(file, null, 2)}\n`, "utf8");
  diskCache.delete(key);
}

export async function loadLibraryFile(key: string): Promise<LibraryFile | null> {
  return readLibraryFile(key);
}

export function buildPathEntry(
  subject: string,
  response: AiPathResponse,
  provider: GenerationProvider,
): CachedPathEntry {
  return {
    version: ENTRY_VERSION,
    subject,
    provider,
    generatedAt: new Date().toISOString(),
    response,
  };
}

export function buildExpansionEntry(
  subject: string,
  depth: number,
  sourceTitles: string[],
  response: AiExpansionResponse,
  provider: GenerationProvider,
): CachedExpansionEntry {
  return {
    version: ENTRY_VERSION,
    subject,
    depth,
    provider,
    generatedAt: new Date().toISOString(),
    sourceTitles,
    response,
  };
}

export { MAX_DEPTH as MAX_CACHE_DEPTH };
